/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 24 01:14:38 GMT 2025
 */

package org.apache.commons.io.output;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayWriter;
import java.io.PipedWriter;
import java.io.Writer;
import org.apache.commons.io.output.CloseShieldWriter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CloseShieldWriter_ESTest extends CloseShieldWriter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        CloseShieldWriter.wrap((Writer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Writer", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CloseShieldWriter closeShieldWriter0 = null;
      try {
        closeShieldWriter0 = new CloseShieldWriter((Writer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Writer", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PipedWriter pipedWriter0 = new PipedWriter();
      CloseShieldWriter closeShieldWriter0 = new CloseShieldWriter(pipedWriter0);
      closeShieldWriter0.close();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      CloseShieldWriter closeShieldWriter0 = CloseShieldWriter.wrap(charArrayWriter0);
      assertNotNull(closeShieldWriter0);
  }
}
