/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 23 18:33:02 GMT 2025
 */

package org.apache.commons.io.input;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.Duration;
import java.time.temporal.ChronoUnit;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingDeque;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.PriorityBlockingQueue;
import org.apache.commons.io.input.QueueInputStream;
import org.apache.commons.io.output.QueueOutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class QueueInputStream_ESTest extends QueueInputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedBlockingDeque<Integer> linkedBlockingDeque0 = new LinkedBlockingDeque<Integer>();
      Duration duration0 = Duration.ofMinutes(1100L);
      QueueInputStream queueInputStream0 = new QueueInputStream(linkedBlockingDeque0, duration0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedBlockingQueue<Integer> linkedBlockingQueue0 = new LinkedBlockingQueue<Integer>();
      Integer integer0 = new Integer(1852);
      linkedBlockingQueue0.add(integer0);
      QueueInputStream queueInputStream0 = new QueueInputStream(linkedBlockingQueue0);
      int int0 = queueInputStream0.read();
      assertEquals(60, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PriorityBlockingQueue<Integer> priorityBlockingQueue0 = new PriorityBlockingQueue<Integer>();
      QueueInputStream queueInputStream0 = null;
      try {
        queueInputStream0 = new QueueInputStream(priorityBlockingQueue0, (Duration) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // waitTime
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedBlockingQueue<Integer> linkedBlockingQueue0 = new LinkedBlockingQueue<Integer>();
      ChronoUnit chronoUnit0 = ChronoUnit.ERAS;
      Duration duration0 = chronoUnit0.getDuration();
      QueueInputStream queueInputStream0 = null;
      try {
        queueInputStream0 = new QueueInputStream(linkedBlockingQueue0, duration0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // long overflow
         //
         verifyException("java.lang.Math", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      QueueInputStream queueInputStream0 = null;
      try {
        queueInputStream0 = new QueueInputStream((BlockingQueue<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // blockingQueue
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      QueueInputStream queueInputStream0 = new QueueInputStream();
      int int0 = queueInputStream0.read();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LinkedBlockingQueue<Integer> linkedBlockingQueue0 = new LinkedBlockingQueue<Integer>();
      Integer integer0 = new Integer(0);
      linkedBlockingQueue0.add(integer0);
      QueueInputStream queueInputStream0 = new QueueInputStream(linkedBlockingQueue0);
      int int0 = queueInputStream0.read();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LinkedBlockingQueue<Integer> linkedBlockingQueue0 = new LinkedBlockingQueue<Integer>();
      Duration duration0 = Duration.ofSeconds((-257L));
      QueueInputStream queueInputStream0 = null;
      try {
        queueInputStream0 = new QueueInputStream(linkedBlockingQueue0, duration0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // waitTime must not be negative
         //
         verifyException("org.apache.commons.io.input.QueueInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      QueueInputStream queueInputStream0 = new QueueInputStream();
      QueueOutputStream queueOutputStream0 = queueInputStream0.newQueueOutputStream();
      assertNotNull(queueOutputStream0);
  }
}
