/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 23 19:09:19 GMT 2025
 */

package org.apache.commons.collections4.bloomfilter.hasher.function;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.collections4.bloomfilter.hasher.HashFunctionIdentity;
import org.apache.commons.collections4.bloomfilter.hasher.function.ObjectsHashIterative;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ObjectsHashIterative_ESTest extends ObjectsHashIterative_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ObjectsHashIterative objectsHashIterative0 = new ObjectsHashIterative();
      byte[] byteArray0 = HashFunctionIdentity.prepareSignatureBuffer(objectsHashIterative0);
      long long0 = objectsHashIterative0.apply(byteArray0, 3);
      assertEquals(1499548305L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ObjectsHashIterative objectsHashIterative0 = new ObjectsHashIterative();
      objectsHashIterative0.getSignedness();
      assertEquals((-2054303016L), objectsHashIterative0.getSignature());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ObjectsHashIterative objectsHashIterative0 = new ObjectsHashIterative();
      objectsHashIterative0.getProcessType();
      assertEquals((-2054303016L), objectsHashIterative0.getSignature());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ObjectsHashIterative objectsHashIterative0 = new ObjectsHashIterative();
      objectsHashIterative0.getName();
      assertEquals((-2054303016L), objectsHashIterative0.getSignature());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ObjectsHashIterative objectsHashIterative0 = new ObjectsHashIterative();
      byte[] byteArray0 = HashFunctionIdentity.prepareSignatureBuffer(objectsHashIterative0);
      long long0 = objectsHashIterative0.apply(byteArray0, 0);
      assertEquals((-2054303016L), long0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ObjectsHashIterative objectsHashIterative0 = new ObjectsHashIterative();
      byte[] byteArray0 = HashFunctionIdentity.prepareSignatureBuffer(objectsHashIterative0);
      long long0 = objectsHashIterative0.apply(byteArray0, (-2544));
      assertEquals(1499548305L, long0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ObjectsHashIterative objectsHashIterative0 = new ObjectsHashIterative();
      String string0 = objectsHashIterative0.getProvider();
      assertEquals((-2054303016L), objectsHashIterative0.getSignature());
      assertEquals("Apache Commons Collections", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ObjectsHashIterative objectsHashIterative0 = new ObjectsHashIterative();
      long long0 = objectsHashIterative0.getSignature();
      assertEquals((-2054303016L), long0);
  }
}
